
version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: xgb_plumber_api
    ports:
      - "8080:8080"
    restart: always

  shiny:
    build:
      context: ./shiny
      dockerfile: Dockerfile
    container_name: xgb_shiny_app
    ports:
      - "3838:3838"
    depends_on:
      - api
    restart: always